"""Deterministic, explainable lead scoring + confidence + channel guardrails.

This is a 1:1 port of ``supabase/functions/_shared/leadScoring.ts``.

It is intentionally NOT AI: plain rule-based logic, so the score and confidence a
user sees are reproducible (identical inputs always produce identical output) and
every point can be explained. The AI model is only used for the narrative and
creative parts of the report -- never for the numbers that decide how qualified a
lead is.

**Parity is enforced by tests.** ``tests/test_lead_scoring.py`` asserts this module
produces byte-identical output to the original TypeScript across a fixture set
generated by executing the TypeScript itself (``tests/golden_lead_scoring.json``).
If you change anything here, regenerate the fixtures and prove the change was
intended -- do not "fix" a failing parity test by editing the expectation.
"""

from __future__ import annotations

import math
import re
from typing import Any, Literal, TypedDict

Tier = Literal["Cold", "Warm", "Hot", "Priority"]
BusinessCategory = Literal["ecommerce", "saas", "local", "agency", "other"]


class ScoreFactor(TypedDict):
    label: str
    points: int
    max: int
    note: str


class LeadScoreResult(TypedDict):
    score: int
    tier: Tier
    reasoning: str
    breakdown: list[ScoreFactor]


class ConfidenceChecklistItem(TypedDict, total=False):
    label: str
    met: bool
    caveat: bool


class ConfidenceResult(TypedDict):
    score: int
    reasoning: str
    checklist: list[ConfidenceChecklistItem]


class ChannelGuardrails(TypedDict):
    category: BusinessCategory
    categoryLabel: str
    matched: bool
    allowedChannels: list[str]


# --------------------------------------------------------------------------
# Category rules -- order matters, first match wins (same as the TS array order)
# --------------------------------------------------------------------------

_CATEGORY_RULES: list[tuple[BusinessCategory, str, re.Pattern[str], list[str]]] = [
    (
        "ecommerce",
        "D2C / E-commerce",
        re.compile(
            r"e-?commerce|d2c|dtc|shop(?:ify)?|retail|apparel|fashion|cosmetic|product brand|online store",
            re.I,
        ),
        [
            "Meta Ads (Facebook/Instagram)",
            "TikTok Ads",
            "Google Shopping",
            "Email/SMS Retention Marketing",
            "Conversion Rate Optimization (CRO)",
            "Influencer/UGC Content",
        ],
    ),
    (
        "saas",
        "B2B SaaS / Software",
        re.compile(
            r"saas|b2b software|software company|platform|startup(?! store)|tech company|app company",
            re.I,
        ),
        [
            "SEO",
            "Google Search Ads",
            "LinkedIn Ads",
            "Content Marketing",
            "Lead Nurturing / Email Sequences",
            "Webinars & Product Demos",
        ],
    ),
    (
        "local",
        "Local / Brick-and-Mortar Business",
        re.compile(
            r"local|restaurant|salon|spa|clinic|dentist|gym|plumb|electrician|contractor|"
            r"law firm|real estate|brick.?and.?mortar|storefront",
            re.I,
        ),
        [
            "Local SEO",
            "Google Business Profile Optimization",
            "Geo-targeted Local Ads",
            "Review & Reputation Management",
            "Community & Social Presence",
        ],
    ),
    (
        "agency",
        "Agency / Professional Services",
        re.compile(
            r"agency|consult|professional services?|accounting|freelance|coach(?:ing)?", re.I
        ),
        [
            "SEO",
            "Content Marketing",
            "LinkedIn",
            "Email Marketing",
            "Referral & Partnership Programs",
        ],
    ),
]

_FALLBACK_CHANNELS = ["SEO", "Google Ads", "Social Media Marketing", "Email Marketing"]


def classify_business(industry: str | None) -> ChannelGuardrails:
    """Classify free-text industry into a known category with a curated channel list."""
    text = (industry or "").strip()
    for category, label, pattern, channels in _CATEGORY_RULES:
        if pattern.search(text):
            return {
                "category": category,
                "categoryLabel": label,
                "matched": True,
                "allowedChannels": list(channels),
            }
    return {
        "category": "other",
        "categoryLabel": text or "Unclassified",
        "matched": False,
        "allowedChannels": list(_FALLBACK_CHANNELS),
    }


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

_NUMBER_RE = re.compile(r"[\d,]+(?:\.\d+)?")


def _js_round(value: float) -> int:
    """JavaScript ``Math.round`` semantics: halves always round UP (toward +inf).

    Python's built-in ``round`` uses banker's rounding (``round(2.5) == 2``), which
    would silently diverge from the TypeScript original on exact .5 values.
    """
    return math.floor(value + 0.5)


def _format_thousands(value: int) -> str:
    """Match JavaScript ``Number.prototype.toLocaleString()`` under the en-US default."""
    return f"{value:,}"


def _extract_monthly_budget(budget: str | None) -> float | None:
    """'$3,000 - $5,000' -> average of the range; a single value -> that value."""
    if not budget:
        return None
    matches = _NUMBER_RE.findall(budget)
    if not matches:
        return None
    values: list[float] = []
    for raw in matches:
        cleaned = raw.replace(",", "")
        if not cleaned or cleaned == ".":
            continue  # a bare "," or "." matched; Number("") is 0 in JS and filtered out
        try:
            number = float(cleaned)
        except ValueError:
            continue
        if math.isfinite(number) and number > 0:
            values.append(number)
    if not values:
        return None
    return sum(values) / len(values)


_GROWTH_KEYWORDS = re.compile(
    r"scale|grow|expand|launch|increase|double|accelerat|new market|enter", re.I
)
_URGENCY_KEYWORDS = re.compile(
    r"now|urgent|asap|immediately|this (quarter|month)|90 days|30 days|need|struggl|"
    r"losing|behind|declin|stall",
    re.I,
)
_MAINTENANCE_KEYWORDS = re.compile(r"maintain|steady|stay|keep up|consistent", re.I)

_CHANNEL_KEYWORDS = [
    re.compile(r"google ads?", re.I),
    re.compile(r"facebook|meta", re.I),
    re.compile(r"instagram", re.I),
    re.compile(r"tiktok", re.I),
    re.compile(r"seo", re.I),
    re.compile(r"email", re.I),
    re.compile(r"linkedin", re.I),
    re.compile(r"content|blog", re.I),
    re.compile(r"influencer", re.I),
    re.compile(r"affiliate", re.I),
    re.compile(r"pr\b|public relations", re.I),
    re.compile(r"referral", re.I),
]


def _s(business: dict[str, Any], key: str) -> str:
    """Read a field as a string, tolerating None/missing/non-string values."""
    value = business.get(key)
    return value if isinstance(value, str) else ""


# --------------------------------------------------------------------------
# Scoring
# --------------------------------------------------------------------------


def compute_lead_score(business: dict[str, Any]) -> LeadScoreResult:
    """0-100 score from five weighted, independently-explainable factors.

    No AI and no randomness: identical input always yields identical output.
    """
    breakdown: list[ScoreFactor] = []

    # 1. Budget fit (max 25)
    monthly_budget = _extract_monthly_budget(_s(business, "budget"))
    budget_points = 0
    if monthly_budget is None:
        budget_note = "No budget provided"
    else:
        pretty = _format_thousands(_js_round(monthly_budget))
        if monthly_budget >= 6000:
            budget_points = 25
            budget_note = f"Budget ~${pretty}/mo supports full-funnel investment"
        elif monthly_budget >= 3000:
            budget_points = 20
            budget_note = f"Budget ~${pretty}/mo supports a multi-channel plan"
        elif monthly_budget >= 1000:
            budget_points = 14
            budget_note = f"Budget ~${pretty}/mo fits a focused single-channel plan"
        else:
            budget_points = 8
            budget_note = f"Budget ~${pretty}/mo is limited"
    breakdown.append(
        {"label": "Budget fit", "points": budget_points, "max": 25, "note": budget_note}
    )

    # 2. Business fit (max 20)
    classification = classify_business(_s(business, "industry"))
    fit_points = 0
    if not _s(business, "industry").strip():
        fit_note = "No industry provided"
    elif classification["matched"]:
        fit_points = 20
        fit_note = f"Clear fit: {classification['categoryLabel']}, a serviceable category"
    else:
        fit_points = 10
        fit_note = "Industry provided but doesn't map to a well-defined category"
    breakdown.append(
        {"label": "Business fit", "points": fit_points, "max": 20, "note": fit_note}
    )

    # 3. Growth potential (max 20) -- from stated goal ambition
    goal = _s(business, "goal").strip()
    growth_points = 0
    if not goal:
        growth_note = "No goal provided"
    elif _GROWTH_KEYWORDS.search(goal):
        growth_points = 20
        growth_note = "Goal signals active growth ambition"
    elif _MAINTENANCE_KEYWORDS.search(goal):
        growth_points = 6
        growth_note = "Goal signals maintenance rather than growth"
    else:
        growth_points = 12
        growth_note = "Goal provided without a clear growth/maintenance signal"
    breakdown.append(
        {"label": "Growth potential", "points": growth_points, "max": 20, "note": growth_note}
    )

    # 4. Marketing maturity (max 20) -- from current channels
    channels_text = _s(business, "currentChannels").strip()
    channel_hits = sum(1 for pattern in _CHANNEL_KEYWORDS if pattern.search(channels_text))
    if not channels_text:
        maturity_points = 5
        maturity_note = "No current channels described (greenfield — lower readiness signal)"
    elif channel_hits == 0:
        maturity_points = 8
        maturity_note = "Channels described but not clearly identifiable"
    elif channel_hits == 1:
        maturity_points = 12
        maturity_note = "Actively running 1 identifiable channel"
    elif channel_hits == 2:
        maturity_points = 17
        maturity_note = "Actively running 2 identifiable channels"
    else:
        maturity_points = 20
        maturity_note = f"Actively running {channel_hits}+ channels — marketing-savvy, sales-ready"
    breakdown.append(
        {
            "label": "Marketing maturity",
            "points": maturity_points,
            "max": 20,
            "note": maturity_note,
        }
    )

    # 5. Goal urgency (max 15)
    urgency_points = 0
    if not goal:
        urgency_note = "No goal provided"
    elif _URGENCY_KEYWORDS.search(goal):
        urgency_points = 15
        urgency_note = "Goal language signals time pressure"
    else:
        urgency_points = 8
        urgency_note = "Goal provided without explicit urgency language"
    breakdown.append(
        {"label": "Goal urgency", "points": urgency_points, "max": 15, "note": urgency_note}
    )

    score = sum(factor["points"] for factor in breakdown)
    if score >= 85:
        tier: Tier = "Priority"
    elif score >= 65:
        tier = "Hot"
    elif score >= 40:
        tier = "Warm"
    else:
        tier = "Cold"

    joined = ", ".join(f"{f['label']} +{f['points']}" for f in breakdown)
    reasoning = f"{score}/100 ({tier}) — {joined}."

    return {"score": score, "tier": tier, "reasoning": reasoning, "breakdown": breakdown}


def compute_confidence(business: dict[str, Any]) -> ConfidenceResult:
    """Confidence as a transparent function of which inputs were actually provided.

    Never an AI-invented percentage.
    """
    checklist: list[ConfidenceChecklistItem] = [
        {"label": "Industry provided", "met": bool(_s(business, "industry").strip())},
        {"label": "Budget provided", "met": bool(_s(business, "budget").strip())},
        {"label": "Target audience provided", "met": bool(_s(business, "audience").strip())},
        {
            "label": "Current channels provided",
            "met": bool(_s(business, "currentChannels").strip()),
        },
        {"label": "Goal provided", "met": bool(_s(business, "goal").strip())},
    ]
    met_count = sum(1 for item in checklist if item["met"])
    score = _js_round((met_count / len(checklist)) * 100)

    # Fixed structural caveat -- this app never has a live analytics connection,
    # so confidence must never imply it does.
    checklist.append(
        {
            "label": "Live analytics not connected (report is based on stated inputs only)",
            "met": False,
            "caveat": True,
        }
    )

    missing = [
        item["label"] for item in checklist if not item["met"] and not item.get("caveat")
    ]
    if not missing:
        reasoning = (
            "All available business inputs were provided — recommendations are grounded "
            "in complete stated information."
        )
    else:
        reasoning = (
            f"Based on {met_count}/{len(checklist) - 1} stated inputs. "
            f"Missing: {', '.join(missing)}. "
            "Recommendations for missing fields are marked as inference, not fact."
        )

    return {"score": score, "reasoning": reasoning, "checklist": checklist}


def compute_lead_score_and_confidence(business: dict[str, Any]) -> dict[str, Any]:
    return {
        "leadScore": compute_lead_score(business),
        "confidence": compute_confidence(business),
    }
